### PR TITLE
Revert "Fix error response parsing"

### PR DESCRIPTION
**Pull request by timolins**
Reverts zeit/now-client#35

### CODE REVIEW

**Comment by leo** [comment]
@OlliV

**Comment by OlliV** [comment]
Uh why? `now-client` is pretty much useless if there is no way to know what went wrong.

**Comment by OlliV** [comment]
Oh, can you instead check if the response exists?

**Comment by timolins** [comment]
Yes, that would be the proper way of doing things. I guess the best approach would be to collect all error types there are and then find a way to represent them in a unified way. I will look into it when I have some time in my hands.

**Pull request merged**
