### PR TITLE
async/await-ify handleRequest

### PR DESCRIPTION
**Pull request by timjacobi**
This replaces the `new Promise` pattern in `handleRequest` with `async/await`

### CODE REVIEW

**Comment by leo** [comment]
We've removed the build step! 😊

**Comment by timjacobi** [comment]
Sorry just curious what that means _We've removed the build step_ :)

**Comment by timolins** [comment]
We completely removed `babel` from this package, as you can see [here](https://github.com/zeit/now-client/commit/0d4c64ce493868315f9b057fae273fcf35af5fa3). This means all code has to run directly inside Node without beeing transpiled. Since Promises have better support than `async/await` at the moment, we can support older versions of Node – even without transpiling.

**Comment by timjacobi** [comment]
Makes sense. Thank you!

**Comment by leo** [comment]
@timolins Thanks for the explanation!

**Pull request closed without merging**
