### PR TITLE
Add support for `teamId`

### PR DESCRIPTION
**Pull request by berzniz**
Added support for `teamId` with the following in mind:

1. No breaking change. The `teamId` is not read from `~/.now.json` to keep the same behavior as before.
2. Tests. All current tests run and pass, but I'm wondering how to add new tests for the team feature. With some guidance I'll gladly add it.

Addresses #63

### CODE REVIEW

**Comment by berzniz** [comment]
That's from Travis CI:
image

Seems like the TEST_NOW_TOKEN is not defined (I have no access to configure Travis CI)

**Comment by timolins** [comment]
Great work! 🙏
But what about tests? I think there should be at least one to make sure it works properly.

**Comment by leo** [comment]
@timolins Great idea! @berzniz would you like to contribute some? I had to disable ava for PRs though, because Travis CI isn't exposing the token to pull requests from different repos.

**Comment by timolins** [comment]
BTW, I just noticed that this feature isn't documented yet – should be an easy fix. 🙂

**Comment by leo** [comment]
https://github.com/zeit/now-client/commit/b0fcace48d76e65702697bd496a6a6a6d904943f

**Comment by berzniz** [comment]
I'd be happy to add tests, but I need a little guidance:
1. Should the test depend on an env variable for the `teamId`?
2. Should we run all the test cases (all `it`s) with a `teamId` provided? Or just test that `this.request` was configured correctly with the `token` and `teamId`?

**Comment by leo** [comment]
@berzniz 

1. Let's set a fixed one for that - @timolins are we using a demo account right now?
2. The latter, I'd say

**Pull request merged**
